server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: brand-service-route
          uri: ${BRAND_SERVICE_URL:http://brand-service:8081}
          predicates:
            - Path=/brands/**
          filters:
            - PrefixPath=/api

        - id: model-service-route
          uri: ${MODEL_SERVICE_URL:http://model-service:8082}
          predicates:
            - Path=/models/**
          filters:
            - PrefixPath=/api