services:
  brand-web:
    build:
      context: ./brand-web
      dockerfile: Dockerfile
    container_name: brand-web
    ports:
      - "3000:80"
    depends_on:
      - gateway-service
    restart: on-failure

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      BRAND_SERVICE_URL: http://brand-service:8081
      MODEL_SERVICE_URL: http://model-service:8082
    depends_on:
      - brand-service
      - model-service
    restart: on-failure

  brand-service:
    build:
      context: ./brand-service
    container_name: brand-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://categories-db:5432/categories_db
      SPRING_DATASOURCE_USERNAME: category_user
      SPRING_DATASOURCE_PASSWORD: category_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      categories-db:
        condition: service_healthy
    restart: on-failure

  model-service:
    build:
      context: ./model-service
    container_name: model-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://elements-db:5432/elements_db
      SPRING_DATASOURCE_USERNAME: element_user
      SPRING_DATASOURCE_PASSWORD: element_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      elements-db:
        condition: service_healthy
    restart: on-failure

  categories-db:
    image: postgres:14-alpine
    container_name: categories-db
    environment:
      POSTGRES_USER: category_user
      POSTGRES_PASSWORD: category_password
      POSTGRES_DB: categories_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U category_user -d categories_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure


  elements-db:
    image: postgres:14-alpine
    container_name: elements-db
    environment:
      POSTGRES_USER: element_user
      POSTGRES_PASSWORD: element_password
      POSTGRES_DB: elements_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U element_user -d elements_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
